### ISSUE TITLE
PostgreSQL Connection Data Obfuscating

### ISSUE THREAD

**Issue by Aryathel** [dubada01/SWTORCombatParser#1]
Hello! I really like your work here, I am using it as inspiration for my own similar project built in Python currently. However, as I was browsing through your source code, I noticed that you left your PostgreSQL database connection information hardcoded in the `PostgresConnection.cs` file, and I wanted to notify you that you should not leave that there, just to be safe. Putting that into an environment variable is the easiest way to prevent others from using it and simply manually message with your data. Also, as a reminder, if you do end up moving the connection information to an environment variable, don't forget to update the password or something along those lines in order to break anyone's connection that might already have the info saved somewhere.

**Comment by dubada01** [comment]
Hello! Thanks for your message! That is a great point, I don't want people accessing the DB and modify leaderboards etc... I'll get the connection string either encrypted or saved off in an environment variable and reset the username/password.Thanks again for reaching out, and if you wouldn't mind I'd love to see what you're working on with your python tool at some point!
-------- Original message --------From: Arya ***@***.***> Date: 9/27/21  7:00 AM  (GMT-07:00) To: dubada01/SWTORCombatParser ***@***.***> Cc: Subscribed ***@***.***> Subject: [dubada01/SWTORCombatParser] PostgreSQL Connection Data Obfuscating (#1) 
Hello! I really like your work here, I am using it as inspiration for my own similar project built in Python currently. However, as I was browsing through your source code, I noticed that you left your PostgreSQL database connection information hardcoded in the PostgresConnection.cs file, and I wanted to notify you that you should not leave that there, just to be safe. Putting that into an environment variable is the easiest way to prevent others from using it and simply manually message with your data. Also, as a reminder, if you do end up moving the connection information to an environment variable, don't forget to update the password or something along those lines in order to break anyone's connection that might already have the info saved somewhere.

**Comment by Aryathel** [comment]
Yeah for sure! I'd love to share it once it gets a little bit further along (I literally just started yesterday). I'm still really new to SWTOR, but as a developer, I can't resist the urge to try making some sort of app around it.
